version: "3.9"

services:
  react-app:
    container_name: react-app
    build: ./front
    ports:
      - "127.0.0.1:3000:3000"
    depends_on: 
      - back-end

  back-end:
    container_name: back-end
    build: ./API-chat
    ports:
      - "127.0.0.1:2999:2999"
